version: '3.3'

services:
  db:
    build: ./
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db:/var/lib/postgresql/data


volumes:
  db:
